# Generated by Django 5.0.6 on 2024-06-26 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_hotel_service_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.hotel'),
        ),
        migrations.AddField(
            model_name='travel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.service'),
        ),
    ]
