# Generated by Django 5.0.6 on 2024-06-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_amount_of_start_hotel_amount_of_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amount_of_star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
