# Generated by Django 5.0.6 on 2024-06-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_hotel_amount_of_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
