# Generated by Django 5.0.6 on 2024-06-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_hotel_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
